#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

git stash -q --keep-index

npm run build
BUILD_RESULT=$?

if [ $BUILD_RESULT -ne 0 ]; then
  echo "Build failed, please fix before committing."
  git stash pop -q
  exit 1
fi

npm run lint --fix
npm run lint:check
LINT_RESULT=$?

if [ $LINT_RESULT -ne 0 ]; then
  echo "Lint failed, please fix before committing."
  git stash pop -q
  exit 1
fi

git stash pop -q
exit 0
